### ISSUE TITLE
Questions: Running Skipper on windows machine, whats the HW setup?

### ISSUE THREAD

**Issue by avishaiNB** [zalando/skipper#1010]
Hi,

Currently I'm running Skipper on **windows server** machine, does anyone knows whats the minimal hardware requirements (CPU, Memory , Disk) for a single node support ~50K req/sec? 

Regards,
Avishai.

**Comment by szuecs** [comment]
Does it run on windows?
I expect that 50k rps is quite hard to achieve, because of the number of sockets. TCP/IP is limited to 16 bit ports range. The hardware requirements for a single machine you should measure. I guess you want to disable all logs to not have I/O and CPU is more important than Memory. 2Gi memory should be fine. Memory depends on the backends you will serve, because you will have some amount of goroutines, which are right now 1 per request and goroutines take 2kB as far as I know + the parsed http request

**Comment by avishaiNB** [comment]
I set up skipper instance on windows machine watching this video: https://opensource.zalando.com/skipper/tutorials/video-howto-build

so i'm happy to announce that it works fine on windows lol :)
About Go plugins (non Linux platforms), isn't custom filters kind of a plugin ?

Regards,
Avishai.

**Comment by szuecs** [comment]
Thanks for reporting that it builds on windows!

[Filters](https://opensource.zalando.com/skipper/reference/filters/) are not [plugins](https://opensource.zalando.com/skipper/reference/plugins/). You could implement your own filters and include them via plugins at runtime, but this only works in Linux.

Did my answer before answers your question or do you have something to add?

**Comment by avishaiNB** [comment]
Yes thank you, i think that for now that should be enough.

Regards,
Avishai.

**Comment by szuecs** [comment]
Great and please share information how much you were able to serve if you test with your hardware spec. :)
