### ISSUE TITLE
Send traffic to all pods when all of them are unready

### ISSUE THREAD

**Issue by thomasabraham** [zalando/skipper#1051]
**Is your feature request related to a problem? Please describe.**
Due to some problem, all pods of a service got unready at the same time. This resulted in the service becoming completely offline.

**Describe the solution you would like**
When all pods are unready, all of them should get traffic. This is the behavior of ALB in AWS. 

**Would you like to work on it?**
Yes, but no background in this project.

**Comment by szuecs** [comment]
@thomasabraham It's not easily possible to do this in Kubernetes, because Kubernetes manages the endpoint list and service ip, which is the source of truth for the dataclient. The dataclient would need to have awareness that you do not want to delete the old endpoints, which is the same as delete  your old deployment.

Personally I would like to close this as "won't fix", because I think it's not the right fix to do.

**Comment by thomasabraham** [comment]
I'm not yet familiar in K8 architecture. I created this issue based on a discussion I had with some colleagues. But after further discussion, we realized that more appropriate solutions would be one or all of the following. 

- Kill pods which are in unready state for more than a configured amount of time. 
- If more than 30% (or other configured value) of pods are unready, start new pods immediately which can be added to load balancer.  

Feel free to close this issue.

**Comment by szuecs** [comment]
You can kill your containers automatically in Kubernetes if you specify a `liveness probe`.
Disclaimer:
I don’t recommend using liveness probe, I am sure you will have unexpected results in overload situations and get downtime that you won’t easily find out how to fix it.
