### ISSUE TITLE
Add option inside plugin to understand to what route is request related

### ISSUE THREAD

**Issue by Shareed2k** [zalando/skipper#1128]
**Is your feature request related to a problem? Please describe.**
yes, First of all i'm using skipper as embeddable lib in my project inside k8s cluster, i need a way inside plugin understand to what route request is related. In my situation i have plugin for route policy so i need a way to fetch specific rules from service to validate the request, so the easiest way i'm see here is get route id from filter context. 

**Describe the solution you would like**
i want to add route id to filter context.

**Describe alternatives you've considered (optional)**
the ugly way is add some static name to plugin as parameter, but it will be limited by k8s ingress, cause we can set few different services inside ingress, and it will b e false positive information.

**Additional context (optional)**
None.

**Would you like to work on it?**
Yes

**Comment by szuecs** [comment]
@Shareed2k As far as I understand you want to build the policy based on route.Id. IS there any specific reason you want to have it work like this?

There are other solutions that should work for you:
1. You can build a custom dataclient, that wraps the kubernetes dataclient, but also fetches your route policy and combines both to create the routes that are fetched from the routing package.
2. You could can build a custom controller that creates a configmap and the kubernetes dataclient will prepend your routes with custom filters read from a file (the mounted configmap written by your policy controller). These defaultfilters can be custom per endpoint use the `kubernetes.Client.defaultFiltersDir` which is set by `kubernetes.Options` via `kubernetes.New()`. (The change was done in https://github.com/zalando/skipper/commit/12b93648a56758dce8d997e52f79a01f975a5831)
3. Depending on the requirements, you could maybe just specify default filters vial command line flag `-default-filters-prepend="filter1() -> filter2()"`. 
4. You could use the `webhook("https://your-auth-server/")` filter, you will get the full request and specify the policy there. https://opensource.zalando.com/skipper/reference/filters/#webhook

As far as I understand 3. won't fit, but 1., 2. and 4. will work.

I would like to not accept your pull request, because we have already 3 different solutions that should work in your case.

**Comment by Shareed2k** [comment]
hmmm ok 1 option i thinks will be good for me thanks...
