### ISSUE TITLE
Add ability to expand access log

### ISSUE THREAD

**Issue by xavivars** [zalando/skipper#1209]
Structured JSON logs are great to analyise Skipper usage. But it would be even better if there was a way to extend what the structured access log actually logs.

**Describe the solution you would like**
I'd like some sort of _hook_ to provide an override to what an accessLog entry contains.

**Describe alternatives you've considered (optional)**
Adding a filter that does the type of accessLog that I want, but I'm not sure how to properly do that so it works properly.

**Additional context (optional)**

**Would you like to work on it?**
Yes/No/Yes, but no time

**Comment by szuecs** [comment]
@xavivars thanks for creating the issue. Are you thinking from a library user perspective to have a hook?
If so what kind of arguments you would like to have as function that you pass as a possible callback?

**Comment by xavivars** [comment]
Hi @szuecs,

Yes, I was thinking of a hook that allowed me to "enrich" the key value pair that is sent to logrus. 

I've been playing with some implementations (by disabling the built-in accessLogger and creating my own as a filter) and I think the perfect (and scalable/extensible) solution would need to allow selecting data from a filter, so you have access to the request, the reponse, the route, etc. 

What about having a key in the state bag that represents a key-value pair so filters can add data to it, and then (maybe via a config flag like `--extend-access-logs`, and a counterpart Options property), that key-value pair gets combined with the one already generated in the access logger?

If that's a feature thay would be welcome, I can try to work on a PR for it

**Comment by xavivars** [comment]
@szuecs, I just created a work-in-progress pull request, just to get some input about the approach.

I am using Skipper as a library with this implementation and it _sort of works_, but I'd like be able to access to some other data in filters (like the Route itself).

Is there any way to do that? Would it be to big of a deal to also pass the routes to the filterContext?

**Comment by szuecs** [comment]
To show the idea, it's good to have the PR open for discussion.
I am not sure about FilterContext having the route. To me is seems a bit of a responsibility problem and it also could lead to dependency cycles. A route has predicates and filters. A FilterContext has access to Request and Response and the Route. It does not sound good to me.

I think there is a need of more details why this needs to be achieved to have access to pass arbitrary key-value data from filters to the logger. Why do you need access to the route from filters?

If we need "only" to do key value pairs, that are set by filters, we can use the stateBag and lookup the statebag from the logger. Do I miss something else?

**Comment by szuecs** [comment]
I talked with @aryszka about the goals and how to achieve this.

The goal is that users can add in request or response filters data to a stateBag that will be passed to the access logs, similar in functionality to the current [`flowId()` filter](https://opensource.zalando.com/skipper/reference/filters/#flowid). For example we can have a filter to control whether the chosen backend gets into the access log or not. Like this we can have it chosen per route, if we want to log this information or not. 

The route information is another story, I think we should have a function to decouple the data from the implementation here. We have the information in `context.route.Id` (`routing.Route` has an `eskip.Route`), but we should provide a way to look this up in favor of using the ID directly. I want to make sure we can change what we log without breaking the lookup. 
Therefore I suggest to have a method on top of `routing.Route`, that returns a lookupID, which can  in this PR just return `eskip.Route.Id`. We can put this into the access log via `proxy.ServeHTTP()` which has the `context.Route` and access to `context.stateBag` to put the lookupID into the `additional` map you pass to `logging.LogAccess()`.

To be able to track back from the access log to the route, we need to add a function to the supportListener in `routing.ServeHTTP`. We should have a a `GET` endpoint for `/route/:lookupid`, which returns the route in eskip format for the given lookupID.

I personally want to have the possibility to reduce the I/O in the logs, because logs per request can add up in latency and throughput.

**Comment by xavivars** [comment]
Thanks for the feedback, and for deeper thoughts about this feature.

I just have a question: do we need to bundle the changes of exposing the route ID in this same PR?

As I see it, with the current implementation, it's already possible for filters to add arbitrary data (non-route related).

I'm happy to implement the other changes suggested, but merging the PR as it is would already be great for us.
