### ISSUE TITLE
Multiple methods in Method predicate

### ISSUE THREAD

**Issue by buzzlighty** [zalando/skipper#1272]
**Is your feature request related to a problem? Please describe.**
I need to use separate filters for separate HTTP Methods but same path. E.G. I need to modify body of the request only for PUT,POST and PATCH. This will cause configuration duplication as only single method is allowed for predicate.

Example:
```
put_operations: Path("...") && Method("PUT")
 -> modPath("/some-path/", "/another-path")
 -> modifyBody()
 -> "https://google.com";

post_operations: Path("...") && Method("POST")
 -> modPath("/some-path/", "/another-path")
 -> modifyBody()
 -> "https://google.com";

operations: Path("...")
 -> modPath("/some-path/", "/another-path")
 -> "https://google.com";
```

Would become:
```
put_operations: Path("...") && Method("PUT", "POST", "PATCH")
 -> modPath("/some-path/", "/another-path")
 -> modifyBody()
 -> "https://google.com";

operations: Path("...")
 -> modPath("/some-path/", "/another-path")
 -> "https://google.com";
```

There also might be other use cases for that.

**Describe the solution you would like**
Allow `Method` predicate accept an array instead of single value.

**Would you like to work on it?**
Yes, but I might be missing some details, on why it's not already done.

**Comment by szuecs** [comment]
@buzzlighty thanks fir the issue, makes a lot of sense!

@aryszka can we do varargs easily for Method predicate?
I mentioned it in https://github.com/zalando/skipper/issues/623#issuecomment-382832728, but TBH I don't remember why we did not do it.

**Comment by buzzlighty** [comment]
What do you think, either it is better to introduce new predicate `Methods` or leave `Method` for backward compatibility. Latter may confuse one, who reads code, though.

**Comment by szuecs** [comment]
If Methods, we should put this into predicates/builtin/methods.go because we want to move all predicates into this directory. We plan to have a breaking change some day, but not now. I will check with @aryszka and respond with a direction for your proposed change.

**Comment by aryszka** [comment]
let's create a new predicate, called "Methods", and put in the predicates/methods/methods.go, so that the package name would become "methods", too.

One reason is having the legacy "Method" field on the eskip.Route objects. The canonical way of defining new predicates is indeed to create a new PredicateSpec.

---

The anecdotal reason for not having varargs in the Method predicate is that we wanted to avoid not explicit 'OR' relationships between predicates, but also hidden ones. In reality, we are not entirely consistent with this convention, regarding the hidden 'OR' relationships, because e.g. it is trivial to define such ORs in predicates where regexp is allowed. The topic of a major release popped up again recently, where would cleanup some legacy inconsistencies with a breaking release, these problems should be addressed, too.

**Comment by buzzlighty** [comment]
Please see https://github.com/zalando/skipper/pull/1308
