### ISSUE TITLE
Question: eskip routes using ingress resources VS etcd

### ISSUE THREAD

**Issue by kolbis** [zalando/skipper#1279]
We are running skipper as ingress controller on our k8s cluster. 
According to the documentation, it is recommended to use ingress resources (and k8s data client) to configure routes.
it implies that there should always be a developer/devops to create the routes.

Given the above I have a few questions / best practices:
1. why is it recommended to use ingress resources to configure routes?
2. what is the best practice, if we would like to create routes by users which do not have access to the k8s cluster? (for example provide an administration site, where users can enter new routes which will be appended to skipper)
3. Is there a known lib that provide admin capability / API to create eskip routes?

**Comment by szuecs** [comment]
@kolbis our main idea for the kubernetes dataclient is, that we enable devops organzations. For us it means developers own the whole stack including the loadbalancer, and in order to deploy they create an ingress resource.
If your idea is different as you stated, it means you can use a different [dataclient](https://opensource.zalando.com/skipper/operation/deployment/), for example [etcd](https://opensource.zalando.com/skipper/data-clients/etcd/).
How to feed etcd with routes, would be up to you and you are free to create a UI for this.
It's possible to enable multiple dataclients running at the same time, but we do not use it ourselves.

You can also build your [own](https://opensource.zalando.com/skipper/tutorials/development/#dataclients) and use skipper as library. In the past we experimented with inkeeper API, but we deprecated the use of it and we might remove support for inkeeper in the future.

**Comment by kolbis** [comment]
@szuecs thank you for the response.
It does clears up some of my questions.

> In the past we experimented with inkeeper API, but we deprecated the use of it and we might remove support for inkeeper in the future

- why did you depricated it?
- Why do you plan to remove support for inkeeper?

**Comment by szuecs** [comment]
Inkeeper is not able to handle so many updates, as far as I remember it was less than 10000 routes and we have  one skipper with >200000 routes. Basically it was a unsuccessful test, that is not removed because we plan a breaking change to clean more things up. Everything marked as deprecated will be removed.

To answer your 3. question:
In skipper project you find ./cmd/eskip/ which builds a binary that uses ./eskip/ library to push route updates to etcd for example. See also https://godoc.org/github.com/zalando/skipper/eskip and https://godoc.org/github.com/zalando/skipper/cmd/eskip
