### ISSUE TITLE
Route requests directly to PHP via FastCGI

### ISSUE THREAD

**Issue by ruudk** [zalando/skipper#1322]
**Is your feature request related to a problem? Please describe.**
When running a PHP application you need `php-fpm`, a fast CGI server. On order to serve traffic to it, you need something that is able to convert HTTP requests to FastCGI requests, like Nginx or Apache.

But having Nginx running only to pass the request coming from Skipper directly to PHP feels like a waste of resources. 

**Describe the solution you would like**
It would be super cool if Skipper would support [FastCGI](https://github.com/yookoala/gofast) so that I can directly connect Skipper to PHP-FPM.

**Would you like to work on it?**
Yes, with some guidance.

**Comment by szuecs** [comment]
Do you think about running this setup outside kubernetes?

For Kubernetes I would not recommend to use this setup.

**Comment by ruudk** [comment]
No, inside Kubernetes. Why wouldn’t you recommend this?

**Comment by szuecs** [comment]
@ruudk :
I think in general FastCGI was done, because of limitations of the load balancer stack in use before.
Within Kubernetes you have hpa + ingress which should be good enough to make your webapp scalable without the need of another reverse proxy. 
So I think it will:
1) be more efficient, if you just use the php application without FastCGI and just reverse proxy to their http handlers.
2) be more reliable, because an outage of one pod with reverse proxy+20 FastCGI applications will have more impact than having one http handler pod down
3) be less prone to error while investigating with opentracing. I saw multiple times, that opentracing showed ingress was slow, but the pod was either restart (easy to see), or they had a `while [ 1 ]; ./start.sh ; done` wrapper script that was hiding that the application crashed all day.

If the proxy client won't get very complicated, I would be fine adding an FCGI implementation.
What do you think @aryszka?

**Comment by ruudk** [comment]
The issue is that there is [no other way](https://serverfault.com/questions/652382/php-servers-without-apache-nginx-cgi-stack) to serve PHP than to use FastCGI.

**Comment by szuecs** [comment]
@ruudk fine for me!
