### ISSUE TITLE
apiusagemonitoring does not support multiple variables in path segment

### ISSUE THREAD

**Issue by AlexanderYastrebov** [zalando/skipper#1345]
**Describe the bug**
apiusagemonitoring filter does not support multiple variables in path segment.

Consider path with multiple variables, e.g. `/exchange-rates/{source-currency}-{target-currency}`

Current implementation splits path into segments by `/`:
https://github.com/zalando/skipper/blob/12212234a5ce108bd98bd46fefc230b68e5443ba/filters/apiusagemonitoring/spec.go#L296
and assumes single variable in the segment:
https://github.com/zalando/skipper/blob/12212234a5ce108bd98bd46fefc230b68e5443ba/filters/apiusagemonitoring/spec.go#L304
https://github.com/zalando/skipper/blob/12212234a5ce108bd98bd46fefc230b68e5443ba/filters/apiusagemonitoring/spec.go#L334-L347

therefore example path would not be properly handled.

**Expected behavior**
Metrics are collected for path with multiple variables in path segment.

**Observed behavior**
Metrics are not collected for path with multiple variables in path segment.

**Comment by szuecs** [comment]
How many var do you expect to be able to use?
This influences the memory usage.

**Comment by tkrop** [comment]
The variables are not the problem here. It just effects the path matching. When we implemented api-monitoring, our rules excluded paths like this. We have changed the rule only recently to allow patterns with multiple variables representing a compound resource identifier. Seems as we have overlooked the effect on API monitoring.

I think we can fix this.

**Comment by AlexanderYastrebov** [comment]
Another approach could be to document it as feature/implementation detail.
