### ISSUE TITLE
cache duration?

### ISSUE THREAD

**Issue by lambertpan** [zalando/skipper#1415]
Nginx seems support the auth-cache-duration, do we have the same functionality in Skipper. If so what is the annotation in use with kubernetes?

**Comment by aryszka** [comment]
Can you link to documentation of auth-cache-duration?

Skipper doesn't cache the outcome of the tokeninfo checks, if this is what you are looking for. It would be a good thing, but it's not yet implemented. In Kubernetes, we use a sidecar currently, that regularly exchanges the required signatures in the background, and executes the validation locally. I am aware that this may require some more effort than if Skipper just simply would do caching, but caching can be tricky, and that's why it is not yet implemented.

**Comment by szuecs** [comment]
@lambertpan which kind of auth filters are you using or is it a general question?

**Comment by AlexanderYastrebov** [comment]
https://github.com/zalando/skipper/pull/2142 implements tokeninfo cache.

**Comment by AlexanderYastrebov** [comment]
nginx ingress docs https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#external-authentication

**Comment by AlexanderYastrebov** [comment]
See https://github.com/zalando/skipper/pull/2142
