### ISSUE TITLE
ingress http to https redirect broken

### ISSUE THREAD

**Issue by szuecs** [zalando/skipper#1694]
**Describe the bug**
Since at least `v0.12.*` the https redirect that we auto provision seems to not work. 

**To Reproduce**

`curl -v http://<url>/ `

**Expected behavior**
should redirect

**Observed behavior**
does not show redirect

**Comment by AlexanderYastrebov** [comment]
The problem seems to be related to ingresses that define path, see [testcase](https://github.com/zalando/skipper/compare/GH-1696-redirect-path?expand=1)

The redirect is added when `redirect.enable || redirect.override`:
https://github.com/zalando/skipper/blob/f5afb6574981d554d60b25ae3d3354dccf2a361b/dataclients/kubernetes/ingress.go#L317-L324

When `r.defaultEnabled==true`
https://github.com/zalando/skipper/blob/f5afb6574981d554d60b25ae3d3354dccf2a361b/dataclients/kubernetes/redirect.go#L36-L38

`r.enable` is never true but `r.override`
https://github.com/zalando/skipper/blob/f5afb6574981d554d60b25ae3d3354dccf2a361b/dataclients/kubernetes/redirect.go#L56

can be true if annotation sets different response code from default, e.g.:
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: foo
  name: qux
  annotations:
    zalando.org/skipper-ingress-redirect-code: "308"
```
So this may serve as a workaround.

The fix might be
```diff
diff --git a/dataclients/kubernetes/redirect.go b/dataclients/kubernetes/redirect.go
index 9ea3711b..f73344b2 100644
--- a/dataclients/kubernetes/redirect.go
+++ b/dataclients/kubernetes/redirect.go
@@ -34,7 +34,7 @@ func createRedirectInfo(defaultEnabled bool, defaultCode int) *redirectInfo {
 }
 
 func (r *redirectInfo) initCurrent(m *definitions.Metadata) {
-       r.enable = !r.defaultEnabled && m.Annotations[redirectAnnotationKey] == "true"
+       r.enable = r.defaultEnabled || m.Annotations[redirectAnnotationKey] == "true"
        r.disable = r.defaultEnabled && m.Annotations[redirectAnnotationKey] == "false"
 
        r.code = r.defaultCode
```
but it breaks some other testcases and I am not sure it is what expected (I feel some kind of contradiction between `r.enable` and `r.disable`)

**Comment by aryszka** [comment]
correct. The current approach was introduced here, where a certain level of ingress specific redirect behavior customization was introduced: https://github.com/zalando/skipper/pull/799

Though, the solution should be instead to check also `defaultEnabled` in addition, where the `enable` and `disable` are currently evaluated.

The reason is that `defaultEnabled` means that the global config enables HTTPS redirects, while `enable` and `disable` represent instructions from a particular ingress spec.

But based on the linked changeset, it looks now that ingress rules with paths never had their own https redirect, only the global redirect. So it seems this is not a regression (will verify).

**Comment by AlexanderYastrebov** [comment]
>  it looks now that ingress rules with paths never had their own https redirect

I have this impression as well though did not check any past revision

**Comment by szuecs** [comment]
We could also do the same as in east west routes and just copy predicates + add XFF predicate, replace the filters and backend.

**Comment by aryszka** [comment]
we also need to support the case when auto is enabled, but somebody wants to disable it for a specific ingress. Otherwise, it sounds legit, and the above proposed update to the condition would do the same. Or do I misunderstand something?

See: https://github.com/zalando/skipper/blob/master/dataclients/kubernetes/redirect.go#L86 (copying the predicates and adding XFF, though it doesn't replace the filters, only appends a redirect)

And see: https://github.com/zalando/skipper/blob/master/dataclients/kubernetes/ingress.go#L317 (this is were an `|| defaultEnabled` is missing)

Is the east-west approach much different?

**Comment by szuecs** [comment]
Do we want to apply 2x the filters?

Regarding the change in line 317, I am fine with that.

**Comment by aryszka** [comment]
as discussed, it doesn't make sense to apply those filters in the redirect routes

**Comment by AlexanderYastrebov** [comment]
If users have e.g. a route group with `inlineContent` (or any shunting filter), current implementation will clone the route,  add `Header("X-Forwarded-For", "http")` predicate and append `redirectTo(308, "https:")` and thus user filter would still apply because it shunts `redirectTo`. I think for redirect routes user filter should be removed as https://github.com/zalando/skipper/issues/1694#issuecomment-763795971 suggests.

**Comment by AlexanderYastrebov** [comment]
Although maybe removing all filters is not a good idea as there might be default filters including protecting `lifo`

**Comment by szuecs** [comment]
Removing lifo() does not hurt because redirect is served by skipper itself so it's nothing we need to throttle to protect backends from each other IMO.

**Comment by szuecs** [comment]
Regarding default vs enabled/disabled. Why we don't have one thing to track if we want to have a redirect?
This looks more complicated, than we need:
https://github.com/zalando/skipper/blob/f5afb6574981d554d60b25ae3d3354dccf2a361b/dataclients/kubernetes/redirect.go#L37-L38
Do I miss something?

**Comment by szuecs** [comment]
fixed with https://github.com/zalando/skipper/pull/1877
