### ISSUE TITLE
Is it possible to use skipper as reverse proxy with AWS ECS cluster

### ISSUE THREAD

**Issue by cabelo-doido** [zalando/skipper#1737]
**Is your feature request related to a problem? Please describe.**
I ever use skipper as reverse proxy and hack some feature like canary with specific condition with my application and It's working perfectly with EKS. But now I change my orchestration to AWS ECS and I like to use skipper as same as I ever done in EKS.

**Describe the solution you would like**
In my understanding "skipper" was compatible with EKS but Is It possible to install It to ECS with same architecture like generate "skipper daemon" (with autoscale) and spread to every instance in ecs cluster and generate skipper controller in some instance.

**Would you like to work on it?**
Yes, but no time,
If It's not compatible with ECS, I like to work on It and make It work but not now.

**Comment by aryszka** [comment]
Hi, thanks for raising this topic.

I am not familiar enough with ECS to have a good grasp of the challenges here, but I also don't see any too big obstacles either. 

As for compatibility: Skipper is just a reverse proxy, so it can be deployed as any application, you just need to figure how to feed Skipper with the right route configuration.

When using in a Kubernetes cluster, the route source is basically the set of Ingress resources, fetched from the Kubernetes API Server. Skipper has a so-called DataClient for Kubernetes, that transforms the Ingress objects to the skipper-common representation of the routes. It considers two things: how to match the requests (Ingress HTTP rules), and where to send them (Kubernetes Service and Endpoint kind resources).

Considering this, when using Skipper in ECS, for you need to figure how to represent the request matching and how represent the targets for the Skipper configuration. Skipper supports implementing custom "DataClients" (a better name would be probably "RouteSource"), that can be used instead of the Kubernetes DataClient, by implementing a simple interface. See:

- https://pkg.go.dev/github.com/zalando/skipper/routing?utm_source=godoc#DataClient
- the CustomDataClients field here: https://pkg.go.dev/github.com/zalando/skipper?utm_source=godoc#Options

How the input for such custom data client would look, depends mainly on the possibilities in ECS and how you use it.

But!!! :)

If we are not talking about a lot applications, then you can also try to evaluate some simpler approaches, using the plain native Skipper route configuration format: eskip. You can try:

- using an eskip file from a shared FS mount
- using the recently released remote file
- using etcd (might a bit rusty, as to our knowledge not used for a long time)

Are you interested in evaluating your use case by using eskip files? In that case useful links can be:

- https://opensource.zalando.com/skipper/data-clients/etcd/
- https://opensource.zalando.com/skipper/data-clients/eskip-file/

(The docs for the eskip file don't contain it yet, but you can also use an http(s) endpoint instead of a plain file path by using the http: or https: schema prefix.)

I hope this helps, let us know if you have any questions or other road blocks.

**Comment by xavivars** [comment]
I have skipper deployed in ECS using the remote eskip file functionality @aryszka was referring to, and it's working smoothly

**Comment by szuecs** [comment]
@cabelo-doido @xavivars do you think we miss documentation or should we just close this issue?

**Comment by xavivars** [comment]
I think there's no missing docs... I would close this issue.

**Comment by szuecs** [comment]
Thanks
