### ISSUE TITLE
Kubernetes: HTTP -> HTTPS redirector

### ISSUE THREAD

**Issue by hjacobs** [zalando/skipper#252]
Skipper should support HTTP -> HTTPS redirects out of the box to be used from our [Kubernetes Ingress AWS Controller](https://github.com/zalando-incubator/kube-ingress-aws-controller).

/cc @aryszka @lmineiro

**Comment by hjacobs** [comment]
AFAIK we only have to move a few lines of code from a Zalando-internal repo to this OSS repo :smile:

**Comment by aryszka** [comment]
pssst :D

what i did in other, small scale deployments, was to deploy another skipper instance to do the https redirect. It was another process in the same docker container. What we can consider here is that in Kubernetes this gets nicer, because we can just add another skipper container to the pod with fixed config doing only the redirects. What do you think?

**Comment by hjacobs** [comment]
@aryszka yes, this might do the job :smile:

**Comment by aryszka** [comment]
@hjacobs ok, i'll test it in https://github.com/zalando-incubator/kubernetes-on-aws

**Comment by szuecs** [comment]
@aryszka this was done and runs in production for us for a long time. Is there something missing or can we close this issue?

**Comment by hjacobs** [comment]
@szuecs I think we can close this :smile:
