### ISSUE TITLE
opencensus support

### ISSUE THREAD

**Issue by szuecs** [zalando/skipper#542]
Maybe it's more related to https://github.com/skipper-plugins/ , what do you think about opencensus support @lmineiro ?
It's in the early stages but could be really interesting.
https://opencensus.io/
https://github.com/census-instrumentation/opencensus-go/

Additionally the w3c information about trace context.
https://github.com/w3c/trace-context/issues
https://www.iana.org/assignments/message-headers/message-headers.xhtml

**Comment by lmineiro** [comment]
This is definitely something we should be looking into. We're also evaluating it as an additional abstraction layer on top of opentracing because it standardizes the wire for trace propagation.

We have some people investigating that and evaluating the effort to integrate with vendors that are still not supported. We may end up contributing that to the project.

**Comment by szuecs** [comment]
I guess the new thing is opentelemitry, so closing
