### ISSUE TITLE
loadbalancer optimization

### ISSUE THREAD

**Issue by szuecs** [zalando/skipper#556]
#536 will do a double lookup of routes. As optimization we should change the lbgroup/members.

lbmembers should not be a route, so also not part of the routing tree, but should be a slice of members within a loadbalanced route.

        hello_lb_group: Path("/foo") && LBGroup("hello")
                -> lbDecide("hello", 3)
                -> <loopback>;
        hello_1: Path("/foo") && LBMember("hello",0)
                -> "http://127.0.0.1:12345";
        hello_2: Path("/foo") && LBMember("hello",1)
                -> "http://127.0.0.1:12346";
        hello_3: Path("/foo") && LBMember("hello",2)
                -> "http://127.0.0.1:12347";

The member routes hello_1 hello_2 hello_3 would not be part of the routing tree, but part of the route  hello_lb_group. Everything else, for example <loopback>, should stay the same.

This will also make it easy to build different loadbalancer algorithms on top of the member slice, because these can be implemented on the current slice of members and chosen per route.

As a proposed solution we would have only one route and not use `<loopback>`.
We would use something similar to this as target, options: 
- `<lbgroup algorithm=roundrobin(args_if_required) [ep1, ep2, ..]>`
- shorter version: `<RR [ep1 ep2 ep3]>`

Another idea from @aermakov-zalando was to enhance this also with options like `retry` that could be enabled to the `lbgroup`.

**Comment by aermakov-zalando** [comment]
I'd suggest adding support for more dynamic forms of this. For Kubernetes, for example, the users would want to just specify the endpoint name & namespace in the rule and have it expand into an automatically refreshed list of backends inside Skipper. This was requested a few times already and is impossible to do in the current setup without going through the Service IP that has tons of issues. It would also look nicer in Skipper route table dump, because you'd see something like `<lbgroup algorithm=… target=kube_endpoint(default, foo)>` instead of `<lbgroup algorithm=… target=addresses(<list of 100 IPs)>`.
