### ISSUE TITLE
HttpOnly cookies are not being set

### ISSUE THREAD

**Issue by stevoPerisic** [zalando/skipper#606]
Calling APIs that return HttpOnly cookies back in the Set-Cookie header are not persisting on the browser.

**Comment by aryszka** [comment]
Hi @stevoPerisic , thanks for posting this issue!

Could you please provide some more details? What does the Set-Cookie header contain that is sent by the API, and is there a difference between this header and what skipper returns?

By default, Skipper copies all the cookies verbatim, just like any other header, without knowing that they are cookies. This is also means that if the cookie has a domain, it has to match the domain of the URL that browser is connecting to.

I tried to reproduce this issue just now, but it worked as expected. I had to use a URL like www.localhost.localdomain, otherwise the browser didn't accept it.

**Comment by stevoPerisic** [comment]
Hi @aryszka here are some details.
I have an eskip file with a route set to a domain that hosts APIs. There is an API that needs to be called to create a session with the server. The AJAX call is made from the front end after the page loads. It goes out and comes back ok. However the "set-cookie" header contains HttpOnly cookies that do not get set (are not visible in the dev tools). A subsequent call that is made does not make available the secure cookies to the API server.

I hope that helps and thank you!

**Comment by aryszka** [comment]
Thanks for the details.

Just to be sure, is the Domain property of the cookie the one of the proxy, or is it the domain of the backend API?

Could you check if your setup is different regarding the cookie from my test described below? I simulated the backend API with a skipper running this route:

```
*
  -> setResponseHeader("Set-Cookie", "test=abc; Path=/; Domain=localhost.localdomain; HttpOnly")
  -> status(200)
  -> <shunt>
```

...and ran a proxy skipper with this route, on port 80 for the test:

```
* -> "http://localhost:9090"
```

and accessed it from the browser through http://localhost.localdomain, and the browser sent the cookies on the sub-sequent requests.

**Comment by stevoPerisic** [comment]
The set-cookie value is like this:
```Set-Cookie:[cookiename=abc; path=/; HttpOnly; Secure]```

**Comment by stevoPerisic** [comment]
And the API is on a different domain.

**Comment by aryszka** [comment]
I updated the above experiment:

- removed the domain from the cookie
- added the secure property

so that backend route looks like this:

```
*
  -> setResponseHeader("Set-Cookie", "test=abc; Path=/; HttpOnly; Secure")
  -> status(200)
  -> <shunt>
```

This should match the cookie that you described. Started the proxy on HTTPS 443 with self-signed certificate, and everything worked as expected: the browser accepted the cookie and sent it with the sub-sequent requests.

I'd need some more input, but not really sure at the moment what to check.

**Comment by stevoPerisic** [comment]
Ok, I have tried the test as you suggested and set up a route like so:
```
test: Path("/test/*")   -> setResponseHeader("Set-Cookie", "test=abc; Path=/; HttpOnly; Secure")
                        -> status(200)
                        -> <shunt>;
```
It did **not** set the cookie. See below:
![screen shot 2018-04-03 at 8 47 08 am](https://user-images.githubusercontent.com/1771243/38250092-df106d66-371b-11e8-8fe0-09de81301f94.png)
![screen shot 2018-04-03 at 8 47 19 am](https://user-images.githubusercontent.com/1771243/38250097-e38ab9fa-371b-11e8-89b3-98650339a771.png)

**Comment by stevoPerisic** [comment]
Ok, I think I know what I'm doing wrong... not running a https on my localhost. I'll try that and it should fix it. I appreciate the help and sorry for wasting your time.

**Comment by stevoPerisic** [comment]
@aryszka how can I start a https skipper proxy?

**Comment by aryszka** [comment]
@stevoPerisic no worries, happy that it works now.

starting skipper with https: if you set the -tls-key and -tls-cert command line options, then skipper will automatically start in https. If it's only local testing, then it's fine to run it with self signed certificates. Try generating self signed certificates without passwords:

```
openssl req  -nodes -new -x509  -keyout server.key -out server.cert
```

then start skipper:

```
skipper -tls-key server.key -tls-cert server.cert
```

**Comment by stevoPerisic** [comment]
Awesome. Thanks!
