### ISSUE TITLE
Verify unbound connection/request limit and its impact

### ISSUE THREAD

**Issue by lmineiro** [zalando/skipper#610]
**Hypothesis**
Each edge request gets its own goroutine and memory usage for variables that are request scoped.

With the current timeout, it should be possible for a misbehaving client (or set of them) to exploit Skipper's unbound connection pool to the backends if they take longer to finish serving the requests than the edge throughput.

**Example**
Having a constant throughput of 1000 rps where each request is handled completely by the respective backends in 10ms should result in a baseline of ~100 goroutines and respective memory usage for each in-flight request. If the backend goes through some capacity or operational issues Skipper can become a queue, accepting all the edge requests and waiting for them to be served (or timeout).

**Possible Impact**
Resource exhaustion on the skipper instance due to unbound connection pool

**Comment by szuecs** [comment]
What do you mean by connection? TCP or already HTTP request?

Thanks for the question, it's a good one and as I know you, you are one of them that can test this best.

More background ideas:

There are good arguments to not use a queue for handling TCP connections from dropbox, they use now a stack instead, such that the never drop all connections if they are in an overrun situation. I guess we would have to implement the queue/stack handling ourselves if we have to do so, I would argue that maybe a userland TCP/IP stack would be awesome to use to reduce context switching and solve the 10M concurrent connection problem similar to https://github.com/robertdavidgraham/masscan

In my honest opinion you should try to show that your hypothesis holds, because this is creating a lot of work for the one working on it. Since we use a 2 layer loadbalancing strategy, skipper is not the direct edge, it's behind AWS lb infrastructure.

**Comment by szuecs** [comment]
With https://opensource.zalando.com/skipper/operation/operation/#tcp-lifo and route separation via lifo and lifoGroup https://opensource.zalando.com/skipper/operation/operation/#scheduler we have good countermeasures against exausting of goroutines.
