### ISSUE TITLE
Docker build

### ISSUE THREAD

**Issue by ebuychance** [zalando/skipper#643]
I was wondering if someone could describe how the docker go / skipper builds are made, specifically how you get them so small! < 26mb.

Thanks

**Comment by mikkeloscar** [comment]
The makefile used is this one: https://github.com/zalando/skipper/blob/master/packaging/Makefile#L18-L19

We use [alpine](https://hub.docker.com/_/alpine/) as the base image which is about 5-6MB.
Note that we build a static go binary since alpine has musl instead of glibc, so we don't link against the libc on the build machine. https://github.com/zalando/skipper/blob/master/packaging/Makefile#L10

Hope this clears it up.

**Comment by ebuychance** [comment]
Perfect thanks!
