### ISSUE TITLE
Don't respond with status 500 for timeout errors

### ISSUE THREAD

**Issue by mikkeloscar** [zalando/skipper#654]
See #652 for full context.

When skipper fails to route to a backend e.g. because the pod no longer exists as shown in #652 then it will result in the following error:

```
[APP]time=\"2018-05-25T14:59:56Z\" level=error msg=\"error during backend roundtrip: kube_default__cluster_registry__cluster_registry_stups_zalan_do____cluster_registry_0: context canceled\"
[APP]time=\"2018-05-25T14:59:56Z\" level=error msg=\"Failed to do backend request to http://10.2.108.118:8080: proxy error with code 0, dialing failed false, unwrap: context canceled\"
[APP]time=\"2018-05-25T14:59:56Z\" level=error msg=\"error while proxying, route kube_default__cluster_registry__cluster_registry_stups_zalan_do____cluster_registry__lb_group, status code 500: proxy error with code 0, dialing failed false, unwrap: context canceled\"
<client> - - [25/May/2018:14:59:46 +0000] \"GET /kubernetes-clusters/<cluster_id>?verbose=false HTTP/1.1\" 500 22 \"\" \"zmon-worker/0.1\" 10010 cluster-registry.stups.zalan.do
```

The error `context canceled` means that skipper failed to establish a connection with the backend and timed out after 10s. Responding with a 500 in this case seems wrong to me since it's not really an internal server error but rather a problem routing to the backend. It should either be 504 or 503 to better express what is happening IMO.

WDYT?

For reference the 500 comes from here: https://github.com/zalando/skipper/blob/master/proxy/proxy.go#L690-L694

**Comment by hjacobs** [comment]
I would definitely consider this a bug, we had something similar in the past: #269 

Skipper should never return any "internal server error" for proxy failures.

**Comment by szuecs** [comment]
@mlarsen my assumption was that nerr.Timeout() would catch that condition.
Did you see who is canceling what context to choose the right error code?
I am not sure if you are right here and it should be clear what condition should result in which error code. 
For sure there is a bug in some other code part, because it should result in connection refused and not in a timeout. I bet it’s yet another race condition in dataclient  kubernetes on tear down of a pod.

**Comment by szuecs** [comment]
@mikkeloscar I don't see the log message from https://github.com/zalando/skipper/blob/master/proxy/proxy.go#L690 in your issue. Why you are sure it comes from there?

**Comment by szuecs** [comment]
If https://github.com/zalando/skipper/blob/7102c46b0d1c3557968d5ac1608f2702c331dc9b/proxy/proxy.go#L400-L409, the actual TCP/TLS establishement of the proxy call, returns an error we do not get a 500, because we return a proxy error, which is checked https://github.com/zalando/skipper/blob/7102c46b0d1c3557968d5ac1608f2702c331dc9b/proxy/proxy.go#L848-L849 returning proxyError, which returns in https://github.com/zalando/skipper/blob/7102c46b0d1c3557968d5ac1608f2702c331dc9b/proxy/proxy.go#L1009 using errorResponse() in case of an error. This error will be handled at https://github.com/zalando/skipper/blob/7102c46b0d1c3557968d5ac1608f2702c331dc9b/proxy/proxy.go#L938-L940 with -1 for the special case where TCP/IP could not be established. The PR adds the condition that the error channel of the DialContext could return a context canceled or time exceeded from within the stdlib. In this particular case I set the error to GatewayTimeout.
