### ISSUE TITLE
add all opentracing providers to the container build

### ISSUE THREAD

**Issue by szuecs** [zalando/skipper#765]
https://github.com/zalando/skipper/releases/tag/v0.10.70 added lightstep opentracing container, but we should also add jaegr and instana that we already implemented in https://github.com/skipper-plugins/opentracing

**Comment by mikkeloscar** [comment]
To follow up on your comment here: https://github.com/zalando/skipper/issues/763#issuecomment-417852290 it probably is worth considering moving the tracer plugins into this repository if we are going to build the images from here anyway.

The plugins doesn't really give any benefit because:

1. Must be build against the same libc as skipper binary
2. Must be build against the exactly same version of dependencies.

having it in one repository would solve 2. automatically and make 1. more natural as they would be built together anyway.

**Comment by szuecs** [comment]
@mikkeloscar I think @aryszka had the idea of having them imported as library. I thought about having it similat to "db" (name correct?) package in Go, that use an unamed import to init() the actual implementation of the db driver.

**Comment by arjunrn** [comment]
>     Must be build against the exactly same version of dependencies.

@mikkeloscar It actually get's worse than that. If the plugin or the main package uses vendored dependencies then there is a mismatch of types for the common dependency as described by this issue [here](https://github.com/golang/go/issues/20481). In this the `opentracing-go` dependency. So yes, I would recommend that we move the plugins to this repository make it part of the same top-level module. It may work but I'm not certain.

**Comment by aryszka** [comment]
I agree that it is simpler to use the tracers as a lib in many cases. OTH, not sure of referencing here something that is only an opensource client library that is not useful on its own because it is only a client of an otherwise proprietary service. What do you think about this?

**Comment by szuecs** [comment]
We published all tracing providers in docker containers.
Discussions can be done in comments or mailing list or slack.
