### ISSUE TITLE
Ratelimit based on loadbalancer members / ratelimit group

### ISSUE THREAD

**Issue by szuecs** [zalando/skipper#912]
Let's say you know your backend can handle 100 req/s per instance and you have some autoscaling in place, but you want to make sure you do not hit backends too much. You want to ratelimit, if you have more than 100 req/s for the backend. 
A backend could be an `endpoint` in kubernetes for example.

We should think about how this looks like if we rebuild the loadbalancing route, but we should be able to ratelimit a route based on the backend or loadbalancer member.

**Comment by aryszka** [comment]
i agree that this would make configuring the rate limits easier, because it makes the rate limit configuration independent of the particular routes.

A step more abstract approach that I am thinking about can be grouping by custom labels:

```
rateLimitGroup("groupA", 300, "1m")
```

Where a group can represent a backend or just be a label, and any set of routes could belong this way to the same rate limit group, even ones with multiple backends. The drawback is when we really want to configure rate limits for a given backend, then this labelled configuration becomes somewhat redundant. Probably this should be an additional possibility besides the backend based rate limiting.

**Comment by szuecs** [comment]
I like the idea of a rateLimitGroup via label
