### ISSUE TITLE
Support Websockets.

### ISSUE THREAD

**Issue by angelaigreja** [zalando/skipper#982]
Currently Skipper support the Upgrade connection which is enough for a server usecase.

When a browser client tries to connect, it enforces the usage of the scheme `ws` and `wss` for TLS based connections.

Currently Skipper throws an error here: https://github.com/zalando/skipper/blob/master/proxy/upgrade.go#L193

The RFC for this protocol is https://tools.ietf.org/html/rfc6455

**Comment by aermakov-zalando** [comment]
This is a bug caused by the recent loadbalancing rewrite. `upgrade.go` parses the `Backend` field to determine the scheme, but for Kubernetes service routes this field is usually empty and the real backend URLs are in the `LBEndpoints`. The corresponding code should either use the scheme from the load-balanced URL, or at least pay attention to the `BackendType` field as well.

**Comment by angelaigreja** [comment]
You are right. Thanks for the hint since it made it easy to reproduce locally.

I have a fix and I will push it soon once I write some tests.
