### ISSUE TITLE
rate limiting support for tee()/teenf()

### ISSUE THREAD

**Issue by lgogolin** [zalando/skipper#997]
Would be nice to have rate limiting inside tee()/teenf() functions.

tee/teenf is not only used for performance test on staging env for example. But in My case We also need that so application in staging can generate internal data based on dynamic requests sent to it. 

I can of course, rate limit on endpoint ingress but that generate unnecessary extra costs in AWS because I'm cloning full production traffic across NAT/ALB etc.

**Comment by szuecs** [comment]
Yes sound good to me, but this require an internal change that would move the ratelimit filter to the first position in front of all other request filter handling.
@aryszka what do you think?
For me it's fine, because the use case of ddos/login protection is covered by that, too.
On the other hand, there is also the idea of limit per backend, for example to support backend overrun protection (for example elasticsearch case).

**Comment by aryszka** [comment]
I am not completely sure if I understand it correctly:
@lgogolin ,
- would you like to apply the same rate limiting to the cloned requests from the the tee() filters as to the main request flow, or
- would you like to apply rate limiting to the cloned requests from the tee() filters only, and not limiting or applying independent rate limiting to the main request flow?

@szuecs I guess your suggestion considers the former option. I am not so sure about that approach, because it eliminates some creative use cases, where someone consciously puts a header changing filter in front of the rate limiter to control how it behaves. Let's try to think of a better solution.

**Comment by szuecs** [comment]
@aryszka thanks for your input. I think we should be more flexible, than we are right now with the placing of ratelimits. Basically based on the type of the ratelimiter I would expect to have different placements:
- before filter chain
- after filter chain
- just in front of the backend end call, after  loadbalancer algorithm was applied

**Comment by aryszka** [comment]
if it was possible to execute the rate limiting via shunting at the position of the filter on the request path, then we wouldn't need to handle it separately from the filter chain, and it would solve all three of the above use cases.

**Comment by aryszka** [comment]
correction: the 3rd case would not be actually so trivial this way

**Comment by lgogolin** [comment]
@aryszka I was more thinking about implementing ratelimiting inside tee/teenf functions. 
Because I don't want to play with My prod traffic. I only would like to limit cloned traffic
Something like:

`teenf("http://some-domain.com", 20, "1h")`

**Comment by szuecs** [comment]
Honestly I don’t like special handling inside the `tee` filter.  If we can specify a filter pipeline per backend and we would have a backend for tee, it would be possible to mutate the http request to pass to a  new modified api version.
I am not sure how this would look like, but it would be really nice.

**Comment by szuecs** [comment]
10% to tee backend can be done with:

```
tee: Tee("A") -> ratelimit() -> "https://teeed-backend/";
split: Host("foo.example.org") && Traffic(0.1) -> teeLoopback("A") -> "https://my-backend"
r0: Host("foo.example.org") -> "https://my-backend"
```
